### ISSUE TITLE
Radar view uses left-hand-rule convention, whereas ROS uses right-hand-rule convention

### ISSUE THREAD

**Issue by rfzeg** [alexandrefch/radar-view#1]
Hello @alexandrefch,

very nice project! I noticed that your diagram angles increase in clockwise direction, which is a left-handed coordinate system.
But in ROS the convention is to use the right-hand-rule, so angles would increase in anticlockwise direction.
It might be a design decision of yours, but if not I just wanted to bring this to your attention.

Cheers,

Roberto

**Comment by alexandrefch** [comment]
Thank for this feedback, 

As you mention, it was simply a design decision. But I added a new node parameter named `clockwise` that allow user to choose if diagram is clockwise or not. (Since this commit 80291bb63a15af240e748a0d231fb70945e75ea5)
